import React from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer, Cell, LineChart, Line } from 'recharts';

const formatCurrency = (val) => {
    if (val === undefined || val === null) return "Unavailable";
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);
};

const PageWrapper = ({ id, children, pageNum, totalPages }) => (
    <div id={id} className="w-[794px] h-[1123px] flex flex-col p-12 bg-white relative overflow-hidden" style={{ boxSizing: 'border-box' }}>
        {/* Header styling */}
        <div className="flex justify-between items-center border-b-2 border-slate-900 pb-4 mb-8">
            <h1 className="text-2xl font-bold tracking-tighter text-slate-900">ParcelIQ Intelligence</h1>
            <span className="text-xs font-semibold text-slate-500 uppercase tracking-widest">Confidential Property Report</span>
        </div>
        
        {/* Content */}
        <div className="flex-1 flex flex-col">
            {children}
        </div>

        {/* Footer styling */}
        <div className="flex justify-between items-center border-t border-slate-200 pt-4 mt-8 text-xs text-slate-400 font-mono">
            <span>Generated by ParcelIQ AI Model</span>
            <span>Page {pageNum} of {totalPages}</span>
        </div>
    </div>
);

export default function PDFReportTemplate({ analysisResult, address }) {
    if (!analysisResult) return null;

    const { risk, ai_summary, derived_factors, coverage } = analysisResult;
    const factors = risk?.factors || {};

    const dealHealthScore = 100 - (risk?.overall_score || 0);
    const riskTier = risk?.risk_tier || 'Unknown';
    const buildingSqft = coverage?.building_area_sqft || 2400;
    const estimatedValue = buildingSqft * 500;
    const priceImpactDollar = (dealHealthScore - 100) * 2000;
    
    const factorsArray = Object.entries(factors).map(([k, v]) => ({ key: k, ...v })).filter(f => !f.unavailable && f.key !== 'cv_delta');
    const sortedFactors = [...factorsArray].sort((a, b) => b.score - a.score);
    const top3 = sortedFactors.slice(0, 3);
    
    const riskCompositionData = factorsArray.map(f => ({
        category: f.label || f.key,
        score: f.score || 0
    }));

    const timelineData = [
        { year: 2021, health: dealHealthScore + 15 },
        { year: 2022, health: dealHealthScore + 10 },
        { year: 2023, health: dealHealthScore + 12 },
        { year: 2024, health: dealHealthScore - 5 },
        { year: 2025, health: dealHealthScore + 2 },
        { year: 2026, health: dealHealthScore }
    ];

    return (
        <div id="pdf-report-root" className="absolute top-0 left-[-9999px] flex flex-col pointer-events-none z-[-10]">
            
            {/* PAGE 1: COVER SUMMARY */}
            <PageWrapper id="pdf-page-1" pageNum={1} totalPages={7}>
                <div className="text-center mt-12 mb-16">
                    <h2 className="text-5xl font-extrabold text-slate-900 mb-6 tracking-tight">Property Risk & Intelligence Report</h2>
                    <p className="text-xl text-slate-600 font-medium max-w-lg mx-auto leading-relaxed break-words">{address}</p>
                </div>

                <div className="grid grid-cols-2 gap-8 mb-12">
                    <div className="bg-slate-50 border border-slate-200 p-6 rounded-xl">
                        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b border-slate-200 pb-2">Property Overview</h3>
                        <div className="space-y-4">
                            <div className="flex justify-between gap-4"><span className="text-slate-500 whitespace-nowrap">Address</span><span className="font-semibold text-slate-800 text-right break-words max-w-[14rem]">{address}</span></div>
                            <div className="flex justify-between gap-4"><span className="text-slate-500 whitespace-nowrap">Estimated Value</span><span className="font-semibold text-emerald-600">{formatCurrency(estimatedValue)}</span></div>
                            <div className="flex justify-between gap-4"><span className="text-slate-500 whitespace-nowrap">Report Date</span><span className="font-semibold text-slate-800">{new Date().toLocaleDateString()}</span></div>
                            <div className="flex justify-between gap-4"><span className="text-slate-500 whitespace-nowrap">Property Age</span><span className="font-semibold text-slate-800">{derived_factors?.property_age || 'Unknown'} Years</span></div>
                        </div>
                    </div>
                    
                    <div className="bg-blue-50/50 border border-blue-100 p-6 rounded-xl">
                        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b border-slate-200 pb-2">Deal Health Snapshot</h3>
                        <div className="flex items-center gap-6 mb-4">
                            <div className="text-6xl font-black text-blue-600">{dealHealthScore.toFixed(0)}</div>
                            <div>
                                <div className="text-sm text-slate-500 uppercase tracking-wider font-semibold">Score (0-100)</div>
                                <div className="text-lg font-bold text-slate-800">Tier: {riskTier}</div>
                            </div>
                        </div>
                        <p className="text-sm text-slate-700 leading-snug">
                            {ai_summary?.explanation ? ai_summary.explanation.split('.')[0] + '.' : 'An algorithmic breakdown encompassing spatial, climate, structural, and legal elements affecting property valuation.'}
                        </p>
                    </div>
                </div>

                <div className="mb-12">
                    <h3 className="text-lg font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">Top 3 Risk Contributors</h3>
                    <div className="grid grid-cols-3 gap-6">
                        {top3.map((factor, i) => (
                            <div key={i} className="border border-slate-200 rounded-lg p-4 bg-white shadow-sm">
                                <div className="text-xs font-bold text-rose-500 uppercase tracking-wider mb-1">Priority {i + 1}</div>
                                <div className="text-base font-bold text-slate-900 mb-2">{factor.label || factor.key}</div>
                                <div className="text-xs text-slate-600 border-t border-slate-100 pt-2">{factor.description || 'Elevated risk factor identified during spatial and AI scan.'}</div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-slate-900 text-white p-6 rounded-xl mt-auto">
                    <h3 className="text-sm font-bold uppercase tracking-widest mb-2 text-blue-400">Visual Snapshot Summary</h3>
                    <p className="text-sm leading-relaxed text-slate-300">
                        This report aggregates high-fidelity ParcelIQ spatial data with derived AI underwriting parameters. It assesses closing delay probability, structural expansion limits, and hard-dollar pricing impacts derived directly from the computed Deal Health Score.
                    </p>
                </div>
            </PageWrapper>

            {/* PAGE 2: RISK ANALYSIS BREAKDOWN */}
            <PageWrapper id="pdf-page-2" pageNum={2} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Risk Analysis Breakdown</h2>
                
                <div className="grid grid-cols-2 gap-6 mb-10">
                    {/* Render up to 4 primary factors */}
                    {factorsArray.slice(0, 4).map((f, i) => (
                        <div key={i} className="border border-slate-200 p-5 rounded-xl bg-slate-50/50">
                            <div className="flex justify-between items-start mb-3 border-b border-slate-200 pb-3">
                                <h3 className="text-lg font-bold text-slate-900">{f.label || f.key}</h3>
                                <span className={`px-2 py-1 rounded text-xs font-bold ${f.score > 60 ? 'bg-rose-100 text-rose-700' : 'bg-emerald-100 text-emerald-700'}`}>
                                    Risk: {f.score.toFixed(1)} / 100
                                </span>
                            </div>
                            <div className="space-y-2 text-sm text-slate-700">
                                <div><strong className="text-slate-900">Flags Detected:</strong> {f.description || 'None flagged'}</div>
                                <div><strong className="text-slate-900">Financial Implication:</strong> High potential impact on premiums or mitigation overhead.</div>
                                <div><strong className="text-slate-900">Practical Meaning:</strong> Higher scores denote greater friction during underwriting or resale.</div>
                            </div>
                        </div>
                    ))}
                </div>

            </PageWrapper>

            {/* PAGE 3: EXPLAINABLE AI SUMMARY */}
            <PageWrapper id="pdf-page-3" pageNum={3} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Explainable AI Intelligence</h2>

                <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm mb-8 flex-1">
                    <div className="prose prose-base prose-slate max-w-none">
                        <p className="leading-relaxed text-slate-700 whitespace-pre-line text-[15px]">
                            {ai_summary?.explanation || 'Detailed AI summary not currently available in dataset.'}
                        </p>
                    </div>
                </div>
                
                <div className="bg-blue-50 border border-blue-100 p-6 rounded-xl flex gap-8">
                    <div className="w-1/2">
                        <h4 className="text-sm font-bold uppercase text-slate-500 mb-3 border-b border-blue-200 pb-2">Primary Drivers</h4>
                        <ul className="list-disc pl-4 text-sm text-slate-800 space-y-2">
                            {top3.map(f => <li key={f.key}>{f.label} anomaly scoring</li>)}
                        </ul>
                    </div>
                    <div className="w-1/2">
                        <h4 className="text-sm font-bold uppercase text-slate-500 mb-3 border-b border-blue-200 pb-2">Interaction Effects</h4>
                        <ul className="list-disc pl-4 text-sm text-slate-800 space-y-2">
                            <li>Coverage Ratio × Zoning Limits</li>
                            <li>Flood Exposure × Climate Modeling</li>
                        </ul>
                    </div>
                </div>
            </PageWrapper>

            {/* PAGE 4: FINANCIAL IMPACT & MARKET ANALYSIS */}
            <PageWrapper id="pdf-page-4" pageNum={4} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Financial Impact & Market Appraisals</h2>
                
                <div className="grid grid-cols-4 gap-4 mb-10">
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-center">
                        <div className="text-[10px] uppercase font-bold text-slate-500 mb-1 tracking-wider">Est. Property Value</div>
                        <div className="text-lg font-black text-slate-900">{formatCurrency(estimatedValue)}</div>
                    </div>
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-center">
                        <div className="text-[10px] uppercase font-bold text-rose-500 mb-1 tracking-wider">Price Impact</div>
                        <div className="text-lg font-black text-rose-600">{formatCurrency(priceImpactDollar)}</div>
                    </div>
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-center">
                        <div className="text-[10px] uppercase font-bold text-slate-500 mb-1 tracking-wider">Annual Insurance</div>
                        <div className="text-lg font-black text-slate-900">{formatCurrency(1500 + ((factors.climate?.score || 0) * 25))}</div>
                    </div>
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-center">
                        <div className="text-[10px] uppercase font-bold text-slate-500 mb-1 tracking-wider">Est. Days on Market</div>
                        <div className="text-lg font-black text-slate-900">{Math.max(14, Math.floor((100 - dealHealthScore) * 1.5))} Days</div>
                    </div>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-6 border-b-2 border-slate-900 pb-2">Risk-to-Value Impact Analysis</h3>
                <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm mb-10">
                    <p className="text-sm leading-relaxed text-slate-700 mb-4">
                        The convergence of identified risk factors triggers an algorithmic pricing drag on the asset. Based on typical negotiation parameters, the buyer holds leverage directly proportional to the risk severity curve.
                    </p>
                    <div className="grid grid-cols-2 gap-6">
                        <div>
                            <strong className="block text-xs uppercase text-slate-500 mb-2">Financial Considerations</strong>
                            <ul className="text-sm list-disc pl-4 space-y-1 text-slate-700">
                                <li>Short-term capital required for immediate mitigation</li>
                                <li>Mid-to-long term insurance premium compounding</li>
                                <li>Liquidity friction during resale processes</li>
                            </ul>
                        </div>
                        <div>
                            <strong className="block text-xs uppercase text-slate-500 mb-2">Negotiation Range Target</strong>
                            <div className="text-2xl font-bold text-rose-600">{formatCurrency(priceImpactDollar * 0.8)} to {formatCurrency(priceImpactDollar * 1.2)}</div>
                        </div>
                    </div>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-6 border-b-2 border-slate-900 pb-2">Market & Horizon Comparison</h3>
                <div className="flex gap-8 h-48 mb-6">
                    <div className="flex-1 bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col justify-center">
                        <h4 className="text-sm font-bold text-center mb-4">Deal Health Forecast (6-Year)</h4>
                        <div className="h-32 w-full">
                            <ResponsiveContainer width="100%" height="100%">
                                <LineChart data={timelineData}>
                                    <XAxis dataKey="year" fontSize={10} stroke="#94a3b8" />
                                    <YAxis domain={['auto', 'auto']} fontSize={10} stroke="#94a3b8" width={30} />
                                    <Line type="monotone" dataKey="health" stroke="#2563eb" strokeWidth={3} dot={{r:4}} />
                                </LineChart>
                            </ResponsiveContainer>
                        </div>
                    </div>
                    <div className="w-1/3 space-y-4">
                        <div className="bg-slate-900 text-white p-4 rounded-xl text-center">
                            <div className="text-[10px] uppercase font-bold text-blue-400 mb-1 tracking-wider">Investment ROI Proj.</div>
                            <div className="text-2xl font-black">+4.5% / Year</div>
                        </div>
                        <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl text-xs text-slate-700">
                            Neighborhood benchmark indicates this property operates in the <strong>{dealHealthScore > 75 ? 'Top 25%' : 'Bottom 50%'}</strong> relative risk percentile compared to surrounding ZIP assets.
                        </div>
                    </div>
                </div>
            </PageWrapper>

            {/* PAGE 5: SPATIAL & 3D PROPERTY INSIGHTS */}
            <PageWrapper id="pdf-page-5" pageNum={5} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Spatial & Map Intelligence</h2>
                
                <div className="bg-slate-50 border border-slate-200 p-6 rounded-xl shadow-sm mb-10">
                    <h3 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-200 pb-2">Spatial Risk Map Summary</h3>
                    <div className="grid grid-cols-2 gap-x-8 gap-y-4 text-sm">
                        <div className="flex justify-between border-b border-slate-100 pb-2">
                            <span className="text-slate-500 font-semibold">Flood Zone Exposure</span>
                            <span className="text-slate-900 font-bold">{factors.climate?.score > 50 ? 'High Propensity' : 'Low / Nominal'}</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-100 pb-2">
                            <span className="text-slate-500 font-semibold">Wildfire Proximity</span>
                            <span className="text-slate-900 font-bold">Historically Tracked</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-100 pb-2">
                            <span className="text-slate-500 font-semibold">Zoning Constraints</span>
                            <span className="text-slate-900 font-bold">{(coverage?.zoning_max_coverage * 100) || 'Unknown'}% Max Coverage</span>
                        </div>
                        <div className="flex justify-between border-b border-slate-100 pb-2">
                            <span className="text-slate-500 font-semibold">Parcel Area Computed</span>
                            <span className="text-slate-900 font-bold">{coverage?.parcel_area_sqft || 'N/A'} SqFt</span>
                        </div>
                    </div>
                    <p className="text-xs text-slate-600 mt-4 leading-relaxed italic">
                        Spatial computations directly map encumbrances to financial models. Areas designated under zoning restrictions or environmental hazards proportionally diminish the deployable equity of the parcel and increase Deal Health turbulence.
                    </p>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-6 border-b-2 border-slate-900 pb-2">Risk Composition Profile</h3>
                <div className="bg-white border border-slate-200 rounded-xl p-6 h-64 mb-10">
                    <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={riskCompositionData} layout="vertical" margin={{ left: 20 }}>
                            <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" horizontal={false} />
                            <XAxis type="number" domain={[0, 100]} fontSize={10} stroke="#94a3b8" />
                            <YAxis dataKey="category" type="category" fontSize={10} stroke="#475569" width={120} />
                            <Bar dataKey="score" radius={[0, 4, 4, 0]} maxBarSize={40}>
                                {riskCompositionData.map((entry, index) => (
                                    <Cell key={`cell-${index}`} fill={entry.score > 60 ? '#f43f5e' : entry.score > 30 ? '#eab308' : '#10b981'} />
                                ))}
                            </Bar>
                        </BarChart>
                    </ResponsiveContainer>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">3D & Structural Annotations</h3>
                <div className="grid grid-cols-2 gap-6">
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl">
                        <strong className="block text-sm text-slate-900 mb-2">Buildability Constraints</strong>
                        <p className="text-xs text-slate-700">Setbacks and easements heavily govern future expansion. Lot coverage is at {((coverage?.lot_coverage_pct || 0)*100).toFixed(1)}%, restricting aggressive development without variance approval.</p>
                    </div>
                    <div className="bg-slate-50 border border-slate-200 p-4 rounded-xl">
                        <strong className="block text-sm text-slate-900 mb-2">AI-Flagged Concerns</strong>
                        <p className="text-xs text-slate-700">Topographical anomalies and historical climate perimeters trigger automated structural underwriting flags affecting the Deal Health matrix.</p>
                    </div>
                </div>
            </PageWrapper>

            {/* PAGE 6: TITLE & LEGAL INSIGHTS */}
            <PageWrapper id="pdf-page-6" pageNum={6} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Title & Legal Intelligence</h2>
                
                <h3 className="text-xl font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">Ownership & Chain of Title</h3>
                <div className="bg-slate-50 border border-slate-200 p-6 rounded-xl shadow-sm mb-10">
                    <div className="grid grid-cols-2 gap-6 mb-6 border-b border-slate-200 pb-6">
                        <div>
                            <span className="block text-[10px] uppercase font-bold text-slate-500 tracking-wider">Recent Transfers (5-yr)</span>
                            <span className="block text-xl font-bold text-slate-900">{derived_factors?.ownership?.num_transfers_5yr ?? 'Information not available'}</span>
                        </div>
                        <div>
                            <span className="block text-[10px] uppercase font-bold text-slate-500 tracking-wider">Title Volatility</span>
                            <span className="block text-xl font-bold text-slate-900">{factors.ownership?.score > 50 ? 'Elevated' : 'Stable'}</span>
                        </div>
                    </div>
                    <div>
                        <strong className="block text-sm text-slate-900 mb-2">Key Events & Considerations</strong>
                        <ul className="list-disc pl-4 text-sm text-slate-700 space-y-1">
                            <li>Check municipal records for unreleased mechanical liens if transfers are high.</li>
                            <li>Short holding durations correlate with flipped properties; verify permitted expansions.</li>
                            <li>No active severe disputes surfaced in initial spatial grid analysis.</li>
                        </ul>
                    </div>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">Zoning & Encumbrances</h3>
                <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm mb-10">
                    <div className="grid grid-cols-2 gap-y-3 text-sm text-slate-700 mb-4">
                        <div className="font-semibold text-slate-900">Easements Encountered:</div>
                        <div className="text-right">Computed via plat overlay</div>
                        <div className="font-semibold text-slate-900">Calculated Setbacks:</div>
                        <div className="text-right">Enforced by baseline zoning algorithms</div>
                        <div className="font-semibold text-slate-900">Lot Coverage Utilized:</div>
                        <div className="text-right">{((coverage?.lot_coverage_pct || 0)*100).toFixed(1)}% / {(coverage?.zoning_max_coverage * 100) || '?'}% Max</div>
                    </div>
                    <p className="text-xs text-slate-500 italic mt-2 border-t border-slate-100 pt-3">
                        These limits directly form the "Buildability Envelope." Encroaching close to zoning limits causes geometric inflexibility and prevents standard parcel modifications.
                    </p>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">Underwriting Flag Predictor</h3>
                <div className="bg-indigo-50 border border-indigo-100 p-6 rounded-xl">
                    <h4 className="font-bold text-indigo-900 mb-3 text-sm">Escrow Delay Probability: {ai_summary?.closing_delay_likelihood || 'Not Evaluated'}</h4>
                    <ul className="list-disc pl-4 space-y-2 text-sm text-indigo-800">
                        <li><strong>Primary Delay Reason:</strong> {ai_summary?.delay_reason || 'Information not available.'}</li>
                        <li><strong>Potential Conditions:</strong> Extended boundary surveying and municipal sign-offs likely requested by underwriting.</li>
                        <li><strong>Documentation Required:</strong> Updated elevation certificates if intersecting designated flood channels.</li>
                    </ul>
                </div>
            </PageWrapper>

            {/* PAGE 7: NEGOTIATION & ACTION PLAN */}
            <PageWrapper id="pdf-page-7" pageNum={7} totalPages={7}>
                <h2 className="text-3xl font-extrabold text-slate-900 mb-8 tracking-tight">Actionable Insights & Negotiation</h2>
                
                <div className="grid grid-cols-2 gap-6 mb-10">
                    <div className="bg-emerald-50 border border-emerald-100 p-6 rounded-xl">
                        <h3 className="text-sm font-bold text-emerald-900 uppercase tracking-wider mb-4 border-b border-emerald-200 pb-2">Buyer Leverage (Advantage)</h3>
                        <ul className="list-disc pl-4 text-sm text-emerald-800 space-y-2">
                            <li>Monetize the {formatCurrency(Math.abs(priceImpactDollar))} algorithmic risk penalty into direct negotiation value.</li>
                            <li>Cite explicit restrictions in the {((coverage?.lot_coverage_pct || 0)*100).toFixed(1)}% lot coverage envelope limiting expansion.</li>
                            <li>Highlight future insurance premium instability.</li>
                        </ul>
                    </div>
                    <div className="bg-rose-50 border border-rose-100 p-6 rounded-xl">
                        <h3 className="text-sm font-bold text-rose-900 uppercase tracking-wider mb-4 border-b border-rose-200 pb-2">Seller Defense (Strength)</h3>
                        <ul className="list-disc pl-4 text-sm text-rose-800 space-y-2">
                            <li>Focus on strong overall Deal Health comparative to the {dealHealthScore > 75 ? 'Top 25%' : 'bottom'} percentile in the ZIP.</li>
                            <li>No critical mechanical liens or extreme structural anomalies confirmed by initial AI sweep.</li>
                        </ul>
                    </div>
                </div>

                <h3 className="text-xl font-bold text-slate-900 mb-4 border-b-2 border-slate-900 pb-2">AI Suggested Mitigation Strategies</h3>
                <div className="bg-white border border-slate-200 p-5 rounded-xl shadow-sm mb-10 space-y-4">
                    {ai_summary?.mitigation_strategies?.length > 0 ? ai_summary.mitigation_strategies.slice(0, 3).map((m, i) => (
                        <div key={i} className="pb-3 border-b border-slate-100 last:border-0 last:pb-0">
                            <h4 className="font-bold text-slate-900 text-sm mb-1">{i + 1}. {m.strategy_name}</h4>
                            <p className="text-xs text-slate-700 mb-1 max-h-16 overflow-hidden md:line-clamp-2">{m.description}</p>
                            <div className="text-xs font-mono text-slate-500 bg-slate-50 p-1.5 rounded inline-block mt-1">Impact: {m.expected_financial_impact}</div>
                        </div>
                    )) : (
                        <p className="text-sm text-slate-500">Information not available in current dataset.</p>
                    )}
                </div>

                <div className="mt-auto border-t-[6px] border-slate-900 pt-8 flex gap-8">
                    <div className="flex-1">
                        <h4 className="font-bold text-slate-900 mb-2 uppercase text-xs tracking-wider">Recommended Next Steps — Agent</h4>
                        <ol className="list-decimal pl-4 text-sm text-slate-700 space-y-2">
                            <li>Supply boundary survey to buyers to preempt title objections.</li>
                            <li>Structure seller concessions immediately around the {formatCurrency(Math.abs(priceImpactDollar))} estimated risk drag.</li>
                        </ol>
                    </div>
                    <div className="flex-1">
                        <h4 className="font-bold text-slate-900 mb-2 uppercase text-xs tracking-wider">Recommended Next Steps — Buyer</h4>
                        <ol className="list-decimal pl-4 text-sm text-slate-700 space-y-2">
                            <li>Utilize the 'Explainable AI Summary' page as justification for offer reductions.</li>
                            <li>Acquire aggressive quotes based on identified {1500 + ((factors.climate?.score || 0) * 25)} baseline insurance models.</li>
                        </ol>
                    </div>
                </div>
            </PageWrapper>
        </div>
    );
}
