/**
 * TitleGuard AI — Property Dashboard Container
 * Manages the dashboard layout: map area + sidebar.
 * Rewritten with Tailwind CSS to match the landing page design.
 */
import React, { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Download } from 'lucide-react';
import SpatialVisualizer from './SpatialVisualizer';
import LayerTogglePanel from './LayerTogglePanel';
import RiskScoreCard from './RiskScoreCard';
import AISummaryBox from './AISummaryBox';

function PropertyDashboard({ analysisResult, isLoading, address, onBack, initialLocation }) {
    const [activeLayers, setActiveLayers] = useState({
        floodZone: false,
        wildfireZone: false,
        earthquakeZone: false,
    });

    const handleToggle = useCallback((layerKey) => {
        setActiveLayers((prev) => ({ ...prev, [layerKey]: !prev[layerKey] }));
    }, []);

    const handleExportReport = useCallback(() => {
        if (!analysisResult) return;

        const { risk, ai_summary, derived_factors } = analysisResult;
        
        const formatImpacts = (impacts) => {
            if (!impacts || impacts.length === 0) return 'None';
            return impacts.map(i => `- ${i.category}: ${i.estimate}`).join('\n');
        };

        const formatRecs = (recs) => {
            if (!recs || recs.length === 0) return 'None';
            return recs.map((r, i) => `${i + 1}. ${r}`).join('\n');
        };

        const reportContent = `# TitleGuard AI Risk Report
Property: ${address}

## Risk Overview
Overall Score: ${risk?.overall_score?.toFixed(1) || 'N/A'}/100
Risk Tier: ${risk?.risk_tier || 'N/A'}
Closing Delay Likelihood: ${ai_summary?.closing_delay_likelihood || 'N/A'} (Reason: ${ai_summary?.delay_reason || 'N/A'})

## Detailed AI Analysis
${ai_summary?.explanation || 'No AI summary available yet.'}

## Recommended Actions
${formatRecs(ai_summary?.recommendations)}

## Estimated Financial Impacts
${formatImpacts(ai_summary?.financial_impacts)}

## Extracted Property Data
- Property Age: ${derived_factors?.property_age || 'Unknown'} years
- Build Coverage Ratio: ${((analysisResult?.coverage?.lot_coverage_pct || 0) * 100).toFixed(1)}%
- Easement Encroachment: ${((derived_factors?.easement_encroachment || 0) * 100).toFixed(1)}%
- Recent Ownership Transfers (5yr): ${derived_factors?.ownership?.num_transfers_5yr ?? 'Unknown'}

---
Report auto-generated by TitleGuard AI.
`;

        const blob = new Blob([reportContent], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `TitleGuard_Risk_Report_${address.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }, [analysisResult, address]);

    return (
        <div className="flex min-h-[calc(100vh-5rem)] flex-col">
            {/* Toolbar */}
            <motion.div
                initial={{ opacity: 0, y: -10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.3 }}
                className="flex items-center justify-between border-b border-white/5 bg-background-subtle px-6 py-3"
            >
                <div className="flex items-center gap-3">
                    <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-text-secondary">
                        Property
                    </span>
                    <span className="text-sm font-medium text-text-primary">{address}</span>

                    {isLoading && (
                        <span className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-[10px] font-medium text-primary">
                            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-primary" />
                            Analyzing…
                        </span>
                    )}

                    {analysisResult && !isLoading && (
                        <span className="inline-flex items-center gap-1 rounded-full bg-risk-green/10 px-2 py-0.5 text-[10px] font-medium text-risk-green">
                            ✓ Complete
                        </span>
                    )}
                </div>
                <div className="flex items-center gap-3">
                    {analysisResult && !isLoading && (
                        <button
                            onClick={handleExportReport}
                            className="flex items-center gap-1.5 rounded-lg border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs text-primary transition hover:border-primary/40 hover:bg-primary/20"
                            title="Export Detailed Report as Markdown"
                        >
                            <Download size={14} />
                            <span>Export Report</span>
                        </button>
                    )}
                    <button
                        onClick={onBack}
                        className="rounded-lg border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-text-secondary transition hover:border-white/20 hover:text-text-primary"
                    >
                        ← New Search
                    </button>
                </div>
            </motion.div>

            {/* Main */}
            <div className="flex flex-1 overflow-hidden max-md:flex-col">
                {/* Left Column Area */}
                <div className="flex flex-1 flex-col overflow-hidden bg-background-subtle">
                    {/* Map Area */}
                    <div className="relative flex-1 bg-background-subtle min-h-[50%]">
                        <SpatialVisualizer
                            analysisResult={analysisResult}
                            activeLayers={activeLayers}
                            initialLocation={initialLocation}
                            address={address}
                        />
                        <LayerTogglePanel
                            activeLayers={activeLayers}
                            onToggle={handleToggle}
                        />
                    </div>
                    {/* AI Summary Box under Map */}
                    <div className="max-h-[50%] overflow-y-auto border-t border-white/5 bg-background">
                        <AISummaryBox
                            summaryData={analysisResult?.ai_summary}
                            isLoading={isLoading}
                        />
                    </div>
                </div>

                {/* Sidebar */}
                <motion.div
                    initial={{ x: 40, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ duration: 0.4, delay: 0.15, ease: 'easeOut' }}
                    className="w-[400px] overflow-y-auto overflow-x-hidden border-l border-white/5 bg-background max-lg:w-[340px] max-md:max-h-[50vh] max-md:w-full max-md:border-l-0 max-md:border-t max-md:border-white/5"
                >
                    <RiskScoreCard
                        riskData={analysisResult?.risk}
                        coverageData={analysisResult?.coverage}
                        isLoading={isLoading}
                    />
                </motion.div>
            </div>
        </div>
    );
}

export default PropertyDashboard;
